### ISSUE TITLE
Org capture stopped working

### ISSUE THREAD

**Issue by eeenilsson** [abo-abo/org-mode#1]
Org-capture has been working fine, but now stopped working. Perhaps after an update (not used capture in a while).

C-c c x (ie capture) produces error:

> Invalid file location: nil

My elisp setting :
```

(setq org-capture-templates
      '(("x"
	 "local notes" entry (file+headline (concat (file-name-directory buffer-file-name) "notes.org") "Copied regions")
	 "* %^{Title} %U \n %i")
	)
)
```
Making the path absolute fixes the problem, but I would like to have a relative file path to put notes in the active directory. This has been working until now.

Exchanging the quote  `'` with backquote and adding comma before `concat` (see below) and then evaluating with `C-x e` also fixes the problem, but then I instead get the following error when restarting emacs: 

> Warning (initialization): An error occurred while loading ‘/home/username/.emacs’:
> Wrong type argument: stringp, nil

This is the .el with backquote and comma instead of quote:
```
(setq org-capture-templates
       `(("x"
	 "local notes" entry (file+headline ,(concat (file-name-directory buffer-file-name) "notes.org") "Copied regions")
	 "* %^{Title} %U \n %i")
	)
)
```

**Comment by abo-abo** [comment]
This isn't the official Org-mode repo, just my fork that I keep around to make my config download itself faster. Please report this on the Org mailing list.

**Comment by eeenilsson** [comment]
Ok, sorry! Thanks anyway for your Good work!

Den 26 nov. 2017 5:14 em skrev "Oleh Krehel" <notifications@github.com>:
