### ISSUE TITLE
Org-mode table header in github readme does not work

### ISSUE THREAD

**Issue by mezeipetister** [abo-abo/org-mode#2]
Hi! When I edit my table in my github readme.md, then the header and the whole table is not recognized as a table in github.

As I checked something is about the 

| header A | header B | header C |
|----------+----------+----------|
| .        | ..       | ...      |
| .        | ..       | ...      |
| .        | ..       | ...      |

When I use | instead of + sign, it works like:

| header A | header B | header C |
|----------|----------|----------|
| .        | ..       | ...      |
| .        | ..       | ...      |
| .        | ..       | ...      |

Do you have any solution for this?

**Comment by abo-abo** [comment]
Sorry, no idea.
